version: '2'

services:
  garden:
    build: .
    container_name: garden
#    volumes: #if uncomment need to have node 6.9 on host and install dependencies
#      - ".:/garden"
    command: sleep 43200
    links:
      - "chrome"

  chrome:
    image: selenium/standalone-chrome-debug:2.53.1
    container_name: chrome
    ports:
      - 4444:4444
      - 5900:5900
